spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fornecedor?useTimezone=true&serverTimezone=America/Sao_Paulo
  jpa:
    hibernate:
      ddl-auto: update
